README.md

Updates readme to mention about the service

fix(readme): Mention about the service

---

config/manager/kustomization.yaml
manifests/dragonfly-operator.yaml

This makes the readme use the latest version.

fix(manifests): Update to latest operator version

---

internal/controller/dragonfly_instance.go

When a master is deleted, The termination could take a while
which means there is a possibility of two pods with `role=master`
to exist. If a pod trigger happens in this situation, Unnecessary
reconcilation happens as the controller can assume thats its
a corrupt state.
This commit essentially eliminates this case by removing this label
before electing a new master and thus ensuring that there is only
master all the time. We can be sure that the new master won't be
the currently being deleted pod as we check for the deletion timestamp

fix(dragonfly): remove master label before configuration

---

e2e/dragonfly_pod_lifecycle_controller_test.go
internal/resources/const.go
internal/resources/version.go

The weekly release of dragonfly has fixes around replication.
This will be changed once we do a dragonfly release.

fix(dragonfly): Use weekly release build tag

---

README.md

Fixes https://github.com/dragonflydb/dragonfly-operator/issues/56

fix(readme): Add instruction to delete/uninstall the operator

---

README.md

fix(readme): remove duplicate crd install

---

internal/resources/resources.go

fix(resources): use cluster ip instead of headless svc

---

config/manager/kustomization.yaml
manifests/crd.yaml
manifests/dragonfly-operator.yaml

feat(release): Release DF Operator v0.0.7

---

api/v1alpha1/dragonfly_types.go
config/crd/bases/dragonflydb.io_dragonflies.yaml
e2e/dragonfly_controller_test.go
internal/resources/resources.go

feat(crd): introduce loadbalancer config

---

api/v1alpha1/dragonfly_types.go
api/v1alpha1/zz_generated.deepcopy.go
config/crd/bases/dragonflydb.io_dragonflies.yaml
e2e/dragonfly_controller_test.go
internal/resources/resources.go
manifests/crd.yaml
manifests/dragonfly-operator.yaml

feat(crd): add AclFromSecret field

---

api/v1alpha1/dragonfly_types.go
api/v1alpha1/zz_generated.deepcopy.go
config/crd/bases/dragonflydb.io_dragonflies.yaml
internal/resources/resources.go
manifests/crd.yaml
manifests/dragonfly-operator.yaml

Hey there 👋
This PR adds priorityClassName to dragonfly pods, addressing https://github.com/dragonflydb/dragonfly-operator/issues/132
Please let me know if I'm missing something.

Feature/add PriorityclassName

---

README.md

- Update README
- Remove `Alpha`.
- Add more features so it aligns with the documentation page.

Chore: update README

---

README.md

fix(readme): change example text from CPU to memory

fix(readme): change example text from CPU to memory

---

config/manager/kustomization.yaml
manifests/dragonfly-operator.yaml

feat(version): release v1.1.2 of Operator

---

api/v1alpha1/dragonfly_types.go
config/crd/bases/dragonflydb.io_dragonflies.yaml
e2e/dragonfly_controller_test.go
internal/resources/resources.go

feat(service): add support for custom service name

---

internal/controller/dragonfly_pod_lifecycle_controller.go

fix(failover): failover to available replicas if master is not starting

---

.github/workflows/ci.yml

The helm release github action is not working. Remove the step for now.

fix(github): remove helm release action

---

internal/controller/dragonfly_controller.go
internal/controller/dragonfly_instance.go
internal/controller/util.go

Closes #196 and remove unused code.

fix(rolling-update): avoid replica takeover for single pod instance

---

charts/dragonfly-operator/templates/servicemonitor.yaml
charts/dragonfly-operator/values.yaml

feat(helm): Add ServiceMonitor resource

---

monitoring/grafana-dashboard.json

fix(dashboard): Use correct metric to determine master

---

charts/dragonfly-operator/templates/clusterroles.yaml
charts/dragonfly-operator/templates/serviceaccount.yaml

Fixes #220 and also fixes serviceAccount annotation template configuration.

fix(helm): remove duplicate labels

---

charts/dragonfly-operator/templates/deployment.yaml
charts/dragonfly-operator/values.yaml

Use resources from Values file in rbac proxy container

Use resources from Values file in rbac proxy container

---

internal/controller/dragonfly_controller.go
internal/controller/dragonfly_pod_lifecycle_controller.go

Fixes https://github.com/dragonflydb/dragonfly-operator/issues/251

fix(reconciler): improve naming

---

api/v1alpha1/dragonfly_types.go
api/v1alpha1/zz_generated.deepcopy.go
config/crd/bases/dragonflydb.io_dragonflies.yaml
internal/resources/resources.go

feat(crd): allow adding custom init containers to dragonfly sts

---

api/v1alpha1/dragonfly_types.go
config/crd/bases/dragonflydb.io_dragonflies.yaml

This allow to quickly see status of our dragonflies.
```
$ kubectl get dragonflies.dragonflydb.io -A
NAMESPACE          NAME                 PHASE   ROLLING UPDATE   REPLICAS
app-mina               dragonfly-mina   ready   true                          2
app-ratus               dragonfly-ratus   ready   true                          2
```

feat(crd): add print of some columns

---

monitoring/grafana-dashboard.json

feat: Support separating by namespace on the Grafana dashboard

---

charts/dragonfly-operator/templates/deployment.yaml
charts/dragonfly-operator/templates/service.yaml
charts/dragonfly-operator/templates/servicemonitor.yaml
charts/dragonfly-operator/values.yaml

ServiceMonitor not scraping the correct port.

fix(helm): metrics port for Service and ServiceMonitor resources

---

charts/dragonfly-operator/Chart.yaml
config/crd/bases/dragonflydb.io_dragonflies.yaml
config/manager/kustomization.yaml
manifests/crd.yaml
manifests/dragonfly-operator.yaml

- **feat(manifests): update to latest**
- **bump to v1.1.9 of operator**

bump to v1.1.9 of operator

---

charts/dragonfly-operator/templates/deployment.yaml
charts/dragonfly-operator/values.yaml

Added support for configuring priorityClassName in the Dragonfly Operator deployment to allow better control over pod scheduling priority.
- Added priorityClassName configuration option in values.yaml
- Updated deployment template to support priorityClassName setting
https://github.com/dragonflydb/dragonfly-operator/issues/294

feat(helm): Add priorityClassName support for dragonfly-operator

---

charts/dragonfly-operator/templates/servicemonitor.yaml

Noticed a path was slightly off. I don't think it has much affect, but I figured I'd provide a fix.

fix(helm) Fix service monitor path
