README.md
This commit adds steps to connect to Dragonfly using redis-cli through
the service created by the operator.
=> fix(readme): Add steps to connect to Dragonfly

README.md
The previous resource change was too low causing OOMKills, This updates
the values to be better.
=> fix(readme): Use right resource values

README.md, config/samples/v1alpha1_dragonfly.yaml
Resource requirements too low causing OOMKills sometimes
=> fix(readme): increase demo resource requirements

e2e/dragonfly_controller_test.go, e2e/dragonfly_pod_lifecycle_controller_test.go, e2e/suite_test.go, e2e/util.go
As these tests are more e2e than unit, Its best to move them
into a separate folder so that the difference is obivous and unit
tests can be added separately
=> fix(tests): move to a separate folder

internal/controller/dragonfly_instance.go, internal/controller/dragonfly_pod_lifecycle_controller.go
Now that we mark pods as they get instanced without waiting for all
resources to be created the code cannot expect all pods to be ready
while it configures replication. This adds an extra pod IP Check.
If there is a pod without IP, the controller will wait for the next
pod event which gets triggered automatically once Kubernetes adds the
IP.
=> fix(dfi): check pod ip before marking

manifests/dragonfly-operator.yaml
Updates the manifests used in readme demos to use the
`v0.0.3` version of the Operator.
=> fix(readme): Update manifests to use `v0.0.3`

config/manager/kustomization.yaml, manifests/dragonfly-operator.yaml
This updates the README manifests to use the `docker.dragonfly.io`
registry to pull the Operator.
=> fix(manifests): Use `docker.dragonfly.io` as the registry

api/v1alpha1/dragonfly_types.go, api/v1alpha1/zz_generated.deepcopy.go, config/crd/bases/dragonflydb.io_dragonflies.yaml, e2e/dragonfly_controller_test.go, internal/resources/resources.go
We are running the dragonfly operator in our clusters, and missed some configuration options we would like for the Dragonfly pods.
I added `Annotations` which allows adding annotations.
We use [datadog Autodiscovery](https://docs.datadoghq.com/containers/kubernetes/integrations/?tab=kubernetesadv1#configuration) which works based on these annotations.
I also added `Tolerations` and `Affinity` options so we can configure on which nodes the pods run.
=> feat(resources): Add ability to set Annotations, Affinity and Tolerations

e2e/dragonfly_controller_test.go, internal/controller/dragonfly_instance.go, internal/controller/util.go, internal/resources/const.go, internal/resources/resources.go
Dragonfly operator should use admin port to manage operations on TLS or password enabled dragonfly instances.
=> fix: use admin-port for dragonfly operations

README.md, api/v1alpha1/dragonfly_types.go, config/crd/bases/dragonflydb.io_dragonflies.yaml, internal/resources/resources.go
In order to get authentication working, the operator needed to be updated to communicate with the pods using their configured passwords. I also added support for setting an environment variable and service account, which allows for different methods of setting the password. I believe this satisfies some of the requests in https://github.com/dragonflydb/dragonfly-operator/issues/50
EDIT: since https://github.com/dragonflydb/dragonfly-operator/commit/4465e8082c05fafc34a3f029adba25a1ba8b4ad8, this PR does not modify how the operator communicates with pods.
=> feat(resources): Updated the CRD to support setting environment variables and a service account

e2e/dragonfly_controller_test.go, e2e/util.go
- Improves the redisClient over k8s port-forward abstraction
- Also, Add data tests with PVC
=> feat(e2e): Improve data insert tests

Makefile, e2e/dragonfly_controller_test.go, e2e/dragonfly_pod_lifecycle_controller_test.go, e2e/util.go, internal/controller/dragonfly_controller.go, internal/controller/dragonfly_instance.go, internal/controller/dragonfly_pod_lifecycle_controller.go, internal/controller/util.go
Fixes https://github.com/dragonflydb/dragonfly-operator/issues/93
Currently, We sometimes miss updates when we compare the statefulset
version. This could be stale as update couldn't have propogated already.
This PR fixes that by requeuing the object when an update is made, so
that we retreive the latest version when ran again.
=> fix(updates): re-run loop when update is made 

e2e/dragonfly_controller_test.go, e2e/util.go, hack/print-roles.go, internal/controller/dragonfly_controller.go, internal/controller/dragonfly_pod_lifecycle_controller.go, internal/controller/util.go
Instead of deleting the master, This PR updates the rollout flow to run `repltakeover` on a latest replica which would mark this pod as the master while terminating the old master. When a pod is terminated, Kubernetes automatically recreates it and the pod lifecycle controller will do the needful.
The pod lifecycle controller does react on various instances and tries to corrupt, but we only expect it to handle new pod creations and hence toggle is added to not react on `isRollingUpdate=true` for other events.
=> feat(upgrade): Use repltakeover

api/v1alpha1/dragonfly_types.go, api/v1alpha1/zz_generated.deepcopy.go, config/crd/bases/dragonflydb.io_dragonflies.yaml, internal/resources/resources.go
So, Looks like `--tls_ca_cert_dir` has its own complexity and I think it makes sense to start with a single certificate as specifying the dir requires some processing before
=> fix(cacert): Use `--tls_ca_cert_file` to pass the file

hack/print-roles.go, internal/controller/dragonfly_instance.go, internal/controller/util.go
Instead of waiting 30mins until idle connections are closed (according to go-redis docs) or until GC will handle old tcp file descriptors, it's better to close go-redis TCP connections ASAP
=> fix(redis-client): Close redis clients ASAP

api/v1alpha1/dragonfly_types.go, api/v1alpha1/zz_generated.deepcopy.go, config/crd/bases/dragonflydb.io_dragonflies.yaml, internal/resources/resources.go
Hey there 👋
This PR adds nodeSelectors to dragonfly pods, addressing https://github.com/dragonflydb/dragonfly-operator/issues/80
Please let me know if I'm missing something.
=> Add nodeSelector field to dragonfly spec, which will be added to podSpec in statefulset

api/v1alpha1/dragonfly_types.go, config/crd/bases/dragonflydb.io_dragonflies.yaml, internal/resources/resources.go
See Issue for details: https://github.com/dragonflydb/dragonfly-operator/issues/116
This is my current workaround: https://github.com/ArthurVardevanyan/HomeLab/blob/main/kubernetes/dragonfly-operator/base/kyverno.yaml
Deployed PR: https://github.com/ArthurVardevanyan/HomeLab/pull/63
=> feat(Openshift): Openshift CRD Flag to Ignore fsGroup

api/v1alpha1/dragonfly_types.go, config/crd/bases/dragonflydb.io_dragonflies.yaml, internal/resources/resources.go, manifests/crd.yaml, manifests/dragonfly-operator.yaml
Add a new `memcachedPort` field that would take the port number and pass that to dragonfly pod as arg. Also open the port in the service.
=> feat(crd): add memcached port support

internal/resources/resources.go
The healthcheck script tries to automatically finds out the dragonfly port when HEALTHCHECK_PORT not set. Dragonfly `v1.16` set the last entry (returned by `netstat` command) as the healthcheck port which may or may not be a dragonfly port. Pass the environment to the statefulset containers so that it always set the healthcheck port to dragonfly.
=> fix(resource): add HEALTHCHECK_PORT env in the statefulset

config/default/manager_auth_proxy_patch.yaml, e2e/dragonfly_controller_test.go
=> chore(controller): update kube-rbac-proxy version

config/default/manager_auth_proxy_patch.yaml
The image that we use for rbac-proxy doesn't have 0.17.1 version. The kubebuilder proxy image has the latest `v0.16` version. As a result, the proxy container is not starting. Use the correct latest version.
=> fix(rbac-proxy): use the correct version

api/v1alpha1/dragonfly_types.go, config/crd/bases/dragonflydb.io_dragonflies.yaml, internal/resources/resources.go
=> feat(service): add support for nodePort

.github/workflows/ci.yml
Fixes: https://github.com/dragonflydb/dragonfly-operator/pull/201 which was initially created by https://github.com/dragonflydb/dragonfly-operator/pull/174 
Related effort: https://github.com/dragonflydb/dragonfly-operator/issues/208
=> fix(helm-release): Added back Helm Chart release CI job

internal/controller/dragonfly_pod_lifecycle_controller.go
=> fix: failover if master pod is not ready

api/v1alpha1/dragonfly_types.go, api/v1alpha1/zz_generated.deepcopy.go, config/crd/bases/dragonflydb.io_dragonflies.yaml, internal/resources/resources.go
Allow user to modify `imagePullPolicy` and set it to Never or IfNotPresent
I let `Always` as default to not "break" anything on old setup
=> feat(operator): allow user to modify imagePullPolicy

e2e/dragonfly_controller_test.go, go.mod, go.sum, internal/controller/dragonfly_controller.go
=> fix(reconciler): recreate missing resources

api/v1alpha1/dragonfly_types.go, config/crd/bases/dragonflydb.io_dragonflies.yaml, internal/resources/resources.go
Fix for https://github.com/dragonflydb/dragonfly-operator/issues/197
=> feat(operator): add imagePullSecrets support #197

monitoring/grafana-dashboard.json
Described here: https://github.com/dragonflydb/dragonfly-operator/issues/256#issuecomment-2556772429
These changes will allow grafana to select datasource of type prometheus automatically
=> fix(monitoring): remove datasource hardcode (#256)

internal/controller/dragonfly_instance.go
It relates to the issue 
https://github.com/dragonflydb/dragonfly-operator/issues/289
The operator will skip masters in the termination state and no longer try to reconfigure the replication to these pods.
=> fix: skip terminating pods in getMasterIp

internal/controller/dragonfly_instance.go
Replication role for replicas is actually "slave" and not "replica".
=> fix(pod-lifecycle): improve replication management

Makefile, cmd/main.go, e2e/dragonfly_controller_test.go, e2e/dragonfly_pod_lifecycle_controller_test.go, internal/controller/base_controller.go, internal/controller/dragonfly_controller.go, internal/controller/dragonfly_instance.go, internal/controller/dragonfly_pod_lifecycle_controller.go, internal/controller/util.go, internal/resources/const.go, internal/resources/resources.go
It relates to the issue
https://github.com/dragonflydb/dragonfly-operator/issues/306
I added more checks like `isPodReady(pod)` and `isPodMarkedForDeletion(pod)` and some refactoring
=> fix: dropping data and some refactoring

charts/dragonfly-operator/templates/crds.yaml
Fixing (not only) the https://github.com/dragonflydb/dragonfly-operator/issues/197#issuecomment-2720693870 also for the helm chart.
I just copied `config/crd/bases/dragonflydb.io_dragonflies.yaml` into the `charts/dragonfly-operator/templates/crds.yaml` so all the new values are there. I mainly need the `imagePullSecrets` value, but let's also add the rest. I tested it on my cluster and it works as expected.
=> Align CRD for helm chart

charts/dragonfly-operator/templates/deployment.yaml, charts/dragonfly-operator/values.yaml
**Title:**  Allow to pass extra flags to containers
**Description:** This PR allows to pass extra args to both the rbac proxy and the manager. I mostly need this change in order to configure the logging level/encoding.
=> feat: allow to pass extra args to containers

charts/dragonfly-operator/templates/deployment.yaml
The metrics endpoint only listens on localhost, making it impossible for metrics scrapers (prometheus, victoriametrics) to reach. This PR removes the bind-address arguments (the health probe argument is redundant as it's set to the program's default value), which will allow scrapers to reach the pods.
https://github.com/dragonflydb/dragonfly-operator/pull/281 is probably preferable to this PR, but there have been no reviews from maintainers. I'm hoping that filing a different approach to the issue will get somebody's attention.
Fixes https://github.com/dragonflydb/dragonfly-operator/issues/301
=> fix: Operator chart blocking access to metrics endpoint

charts/dragonfly-operator/templates/_helpers.tpl, charts/dragonfly-operator/templates/service.yaml
This pull request includes changes to the Helm chart to ensure compliance with DNS naming specifications.
* Added a new template definition for `metricsServiceName` to truncate the fullname template to 28 characters and append a suffix, ensuring the total length does not exceed 63 characters. (`charts/dragonfly-operator/templates/_helpers.tpl`)
* Updated the service name in `service.yaml` to use the new `metricsServiceName` template. (`charts/dragonfly-operator/templates/service.yaml`)
fixes #298
=> fix(helm): truncate metrics service name to comply with DNS naming spec

charts/dragonfly-operator/templates/service.yaml
Every other template has `namespace: {{ .Release.Namespace | quote }}`. Only service.yaml is missing it creating problems when deploying declaratively via helmfile. This change brings it to the same standard.
=> Include namespace in service.yaml template

internal/resources/resources.go
volumeclaimtemplates cannot be patched with new labels, this pr rolls back labels added to snapshot volume.
=> fix: backward incompatible due to labels changes for snapshot volume
